### ISSUE TITLE
Choose Python discord API library. 

### ISSUE THREAD

**Issue by ptrks** [patrick--/discord_camera_bot#1]
Plenty of different libraries for Discord integration exist for Python. Let's agree on which one we should use for the project.

**Comment by ptrks** [comment]
If everyone else is okay with it, [discord.py](https://pypi.org/project/discord.py/) looks perfect.

**Comment by kowshikgunda71** [comment]
yeah I was looking over this yesterday,  I  guess  discord.py works it's just that I need to read the documentation over once I will do that today in the evening
